site_name: Sandpolis Documentation
nav:
  - Home: index.md
  - Tutorials:
      - Getting Started: tutorials/getting_started.md
      - Using the desktop client: tutorials/client/gui.md
      - Using the terminal client: tutorials/client/terminal.md
  - Specification:
      - General:
          - Module: specification/module.md
          - Instance: specification/instance.md
      - Instances:
          - Agent: specification/agent.md
          - Server: specification/server.md
          - Distagent: specification/distagent.md
      - Messages:
          - Client/Server: specification/clientserver.md
          - Server/Agent: specification/serveragent.md
      - Plugins:
          - Desktop Plugin: specification/plugins/desktop.md
          - Device Plugin: specification/plugins/device.md
          - Filesystem Plugin: specification/plugins/filesystem.md
          - Shell Plugin: specification/plugins/shell.md
          - Snapshot Plugin: specification/plugins/snapshot.md
          - Update Plugin: specification/plugins/update.md
  - Implementation Reference:
      - Client: application/client.md
      - Server: application/server.md
      - Agent: application/agent.md
      - Networking: application/network.md
theme: readthedocs
markdown_extensions:
  - admonition
