site_name: Sandpolis Documentation
nav:
  - Home: index.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    - Using the desktop client: tutorials/client/gui.md
    - Using the terminal client: tutorials/client/terminal.md
  - Specification:
    - Agent: specification/agent.md
    - Server: specification/server.md
    - Client/Server: specification/clientserver.md
    - Server/Agent: specification/serveragent.md
    - Plugins:
      - Device Plugin: specification/plugin/device.md
      - Filesystem Plugin: specification/plugin/filesystem.md
      - Snapshot Plugin: specification/plugin/snapshot.md
  - Implementation Reference:
    - Client: application/client.md
    - Server: application/server.md
    - Agent: application/agent.md
    - Data Model: application/data_model.md
    - Networking: application/network.md
theme: readthedocs
markdown_extensions:
  - admonition
