site_name: Sandpolis Documentation
nav:
  - Home: index.md
  - Tutorials:
    - Getting Started: tutorials/getting_started.md
    - Using the desktop client: tutorials/client/gui.md
    - Using the terminal client: tutorials/client/terminal.md
  - Specification:
    - Modules:
      - Agent: specification/com.sandpolis.core.agent.md
      - Server: specification/com.sandpolis.core.server.md
      - Deployer: specification/com.sandpolis.core.deployer.md
    - Instances:
      - Vanilla Server: specification/com.sandpolis.server.vanilla.md
    - Plugins:
      - Desktop Plugin: specification/com.sandpolis.plugin.desktop.md
        - Messages: specification/messages/com.sandpolis.plugin.desktop.md
      - Device Plugin: specification/com.sandpolis.plugin.device.md
        - Messages: specification/messages/com.sandpolis.plugin.device.md
      - Filesystem Plugin: specification/com.sandpolis/plugin.filesystem.md
        - Messages: specification/messages/com.sandpolis.plugin.filesystem.md
      - Shell Plugin: specification/com.sandpolis.plugin.shell.md
        - Messages: specification/messages/com.sandpolis.plugin.shell.md
      - Snapshot Plugin: specification/com.sandpolis.plugin.snapshot.md
        - Messages: specification/messages/com.sandpolis.plugin.snapshot.md
      - Update Plugin: specification/com.sandpolis.plugin.update.md
        - Messages: specification/messages/com.sandpolis.plugin.update.md
theme: readthedocs
markdown_extensions:
  - admonition
